package com.example.expensetracker.ui.theme

import androidx.compose.ui.graphics.Color

// A green-seeded Material 3 palette. Money app, green, no apologies.

val LightPrimary = Color(0xFF276B4E)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFAAF2C7)
val LightOnPrimaryContainer = Color(0xFF002114)
val LightSecondary = Color(0xFF4E6355)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD0E8D6)
val LightOnSecondaryContainer = Color(0xFF0B1F14)
val LightTertiary = Color(0xFF3B6470)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFBFEAF8)
val LightOnTertiaryContainer = Color(0xFF001F27)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFF7FBF6)
val LightOnBackground = Color(0xFF191C1A)
val LightSurface = Color(0xFFF7FBF6)
val LightOnSurface = Color(0xFF191C1A)
val LightSurfaceVariant = Color(0xFFDCE5DC)
val LightOnSurfaceVariant = Color(0xFF414942)
val LightOutline = Color(0xFF717972)
val LightOutlineVariant = Color(0xFFC0C9C0)

// The container roles carry the app's cards and sheets. Left undefined they
// fall back to Material's purple-tinted baseline, which clashes with the green.
val LightSurfaceContainerLowest = Color(0xFFFFFFFF)
val LightSurfaceContainerLow = Color(0xFFF1F5F0)
val LightSurfaceContainer = Color(0xFFEBEFEA)
val LightSurfaceContainerHigh = Color(0xFFE5EAE4)
val LightSurfaceContainerHighest = Color(0xFFE0E4DF)
val LightSurfaceDim = Color(0xFFD7DBD5)
val LightSurfaceBright = Color(0xFFF7FBF6)
val LightInverseSurface = Color(0xFF2E312F)
val LightInverseOnSurface = Color(0xFFEFF1EC)
val LightInversePrimary = Color(0xFF8ED5AC)

val DarkPrimary = Color(0xFF8ED5AC)
val DarkOnPrimary = Color(0xFF003824)
val DarkPrimaryContainer = Color(0xFF005236)
val DarkOnPrimaryContainer = Color(0xFFAAF2C7)
val DarkSecondary = Color(0xFFB5CCBB)
val DarkOnSecondary = Color(0xFF213528)
val DarkSecondaryContainer = Color(0xFF374B3E)
val DarkOnSecondaryContainer = Color(0xFFD0E8D6)
val DarkTertiary = Color(0xFFA4CDDC)
val DarkOnTertiary = Color(0xFF053541)
val DarkTertiaryContainer = Color(0xFF234C58)
val DarkOnTertiaryContainer = Color(0xFFBFEAF8)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF191C1A)
val DarkOnBackground = Color(0xFFE1E3DE)
val DarkSurface = Color(0xFF191C1A)
val DarkOnSurface = Color(0xFFE1E3DE)
val DarkSurfaceVariant = Color(0xFF414942)
val DarkOnSurfaceVariant = Color(0xFFC0C9C0)
val DarkOutline = Color(0xFF8B938B)
val DarkOutlineVariant = Color(0xFF414942)

val DarkSurfaceContainerLowest = Color(0xFF0C0F0D)
val DarkSurfaceContainerLow = Color(0xFF191C1A)
val DarkSurfaceContainer = Color(0xFF1D201E)
val DarkSurfaceContainerHigh = Color(0xFF272B28)
val DarkSurfaceContainerHighest = Color(0xFF323533)
val DarkSurfaceDim = Color(0xFF191C1A)
val DarkSurfaceBright = Color(0xFF3F423F)
val DarkInverseSurface = Color(0xFFE1E3DE)
val DarkInverseOnSurface = Color(0xFF2E312F)
val DarkInversePrimary = Color(0xFF276B4E)
